import "./css/globals.css";
import "./css/styles.min.css"
import "react-responsive-carousel/lib/styles/carousel.min.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
